POST http://localhost:8080/api/shorten
Content-Type: application/json

{"url":"http://vk1.com"}

###
GET http://localhost:8080/fAGRw

###
POST http://localhost:8080/
Content-Type: text/html; charset=UTF-8

http://www.mail2.ru


###
POST http://localhost:8080/
Content-Type: text/html; charset=UTF-8

http://bizwxnxs7.com/ednfdysktalcyj/y3fcjueu/pwjidt


###